version: "3.9"
services:
    php-env:
        build: .
        # restart: always
        ports:
            - 9000:80
        volumes:
            - ./src:/var/www/html
            # - ./log:/var/log/apache2
    mysql_db:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            # - MYSQL_DATABASE=myDb
            # - MYSQL_USER=user
            # - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
        - 9001:80
        environment:
        - PMA_ARBITRARY=1
        # volumes:
        # - /sessions